#spring.application.name=microservice-test1

server:
  port: 8082

spring:
  application:
    name: microservice-test1
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: https://microservice-eureka.onrender.com/eureka/