#spring.application.name=microservice-gateway

server:
  port: 8081

spring:
  application:
    name: microservice-gateway
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: microservice-test1
            uri: https://microservice-test1.onrender.com
            predicates:
              - Path=/test1/api/**

          - id: microservice-test2
            uri: lb://microservice-test2
            predicates:
              - Path=/test2/api/**


eureka:
  client:
    service-url:
      defaultZone: https://microservice-eureka.onrender.com/eureka/
